include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [generator/fonts.pb.dart]
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: false
    avoid_types_on_closure_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    constant_identifier_names: true
    directives_ordering: true
    package_api_docs: true
    prefer_single_quotes: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
