name: dynamic_color_testing
description: "A Flutter package to support testing dynamic_color package."
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=3.4.0-17.0.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  dynamic_color:
    path: ../dynamic_color
  # Since this package is an SDK dependency, we need to support a range of versions.
  # See https://github.com/flutter/flutter/blob/main/packages/flutter/pubspec.yaml for current version used by the SDK.
  material_color_utilities: ">=0.2.0 <= 0.13.0"

dev_dependencies:
  flutter_lints: ">=4.0.0 <7.0.0"
