name: dynamic_color_testing
description: "A Flutter package to support testing dynamic_color package."
version: 1.0.0
repository: https://github.com/material-foundation/flutter-packages/tree/main/packages/dynamic_color_testing
issue_tracker: https://github.com/material-foundation/flutter-packages/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+dynamic_color%22

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=3.4.0-17.0.pre"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  # To avoid circular dependancy on the next `dynamic_color` major version bump.
  dynamic_color: ">=2.0.0 <4.0.0"
  material_color_utilities: ^0.13.0
  material_ui: ^1.0.0


dev_dependencies:
  flutter_lints: ^6.0.0
