name: Feature request
description: Suggest an enhancement.
labels: ["enhancement", "triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package does this concern?
      options:
        - All packages
        - google_fonts
        - dynamic_color
        - adaptive_breakpoints
        - adaptive_navigation
        - adaptive_components
        - symbols
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened?
      description: What happened? What did you expect to happen? How can we reproduce the issue?
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.

        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.

        **Additional context**
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
