import 'package:flutter/material.dart';

List<ColorScheme> colorSchemeFromList(List<int> colors) {
  return [
    ColorScheme(
      brightness: Brightness.light,
      primary: Color(colors[0]),
      onPrimary: Color(colors[1]),
      primaryContainer: Color(colors[2]),
      onPrimaryContainer: Color(colors[3]),
      secondary: Color(colors[4]),
      onSecondary: Color(colors[5]),
      secondaryContainer: Color(colors[6]),
      onSecondaryContainer: Color(colors[7]),
      tertiary: Color(colors[8]),
      onTertiary: Color(colors[9]),
      tertiaryContainer: Color(colors[10]),
      onTertiaryContainer: Color(colors[11]),
      error: Color(colors[12]),
      onError: Color(colors[13]),
      errorContainer: Color(colors[14]),
      onErrorContainer: Color(colors[15]),
      surface: Color(colors[16]),
      onSurface: Color(colors[17]),
      onSurfaceVariant: Color(colors[18]),
      surfaceContainerLowest: Color(colors[19]),
      surfaceContainerLow: Color(colors[20]),
      surfaceContainer: Color(colors[21]),
      surfaceContainerHigh: Color(colors[22]),
      surfaceContainerHighest: Color(colors[23]),
      inverseSurface: Color(colors[24]),
      onInverseSurface: Color(colors[25]),
      inversePrimary: Color(colors[26]),
      outline: Color(colors[27]),
      outlineVariant: Color(colors[28]),
    ),
    ColorScheme(
      brightness: Brightness.dark,
      primary: Color(colors[29]),
      onPrimary: Color(colors[30]),
      primaryContainer: Color(colors[31]),
      onPrimaryContainer: Color(colors[32]),
      secondary: Color(colors[33]),
      onSecondary: Color(colors[34]),
      secondaryContainer: Color(colors[35]),
      onSecondaryContainer: Color(colors[36]),
      tertiary: Color(colors[37]),
      onTertiary: Color(colors[38]),
      tertiaryContainer: Color(colors[39]),
      onTertiaryContainer: Color(colors[40]),
      error: Color(colors[41]),
      onError: Color(colors[42]),
      errorContainer: Color(colors[43]),
      onErrorContainer: Color(colors[44]),
      surface: Color(colors[45]),
      onSurface: Color(colors[46]),
      onSurfaceVariant: Color(colors[47]),
      surfaceContainerLowest: Color(colors[48]),
      surfaceContainerLow: Color(colors[49]),
      surfaceContainer: Color(colors[50]),
      surfaceContainerHigh: Color(colors[51]),
      surfaceContainerHighest: Color(colors[52]),
      inverseSurface: Color(colors[53]),
      onInverseSurface: Color(colors[54]),
      inversePrimary: Color(colors[55]),
      outline: Color(colors[56]),
      outlineVariant: Color(colors[57]),
    ),
  ];
}
