# Builds and deploys example web apps for each of the packages to GitHub Pages
name: Deploy examples to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Determine which packages have example apps
  find-example-apps:
    runs-on: ubuntu-latest
    outputs:
      example-apps: ${{ steps.find-example-apps.outputs.example-apps }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: man ls
      - name: Find example apps
        id: find-example-apps
        # Outputs a JSON list of packages with example apps, e.g. ["dynamic_color", ...]
        run: |
          echo "::set-output name=example-apps::$(ls -d */example | xargs dirname | jq -R -s -c 'split("\n")[:-1]')"
        working-directory: packages

  # Build example web apps job
  build:
    needs: find-example-apps
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        package: ${{ fromJson(needs.find-example-apps.outputs.example-apps) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: 'stable'

      - name: Build Flutter web app
        run: flutter build web -v --release --output /tmp/${MATRIX_PACKAGE} --base-href /${GITHUB_EVENT_REPOSITORY_NAME}/${MATRIX_PACKAGE}/
        working-directory: packages/${{ matrix.package }}/example
        env:
          MATRIX_PACKAGE: ${{ matrix.package }}
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Upload web build temporarily
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.package }}
          path: /tmp/${{ matrix.package }}
          retention-days: 1

  # Upload pages artifact to pages job
  upload-to-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all web builds
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: '.'

  # Deploy job
  deploy-pages:
    needs: upload-to-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
