# Builds and deploys example web apps for each of the packages to GitHub Pages
name: Deploy examples to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Determine which packages have example apps
  find-example-apps:
    runs-on: ubuntu-latest
    outputs:
      example-apps: ${{ steps.find-example-apps.outputs.example-apps }}
    steps:
      - uses: actions/checkout@v4
      - name: Find example apps
        id: find-example-apps
        # Outputs a JSON list of packages with example apps, e.g. ["dynamic_color", ...]
        run: |
          example_apps=$(ls -d */example | xargs dirname | jq -R -s -c 'split("\n")[:-1]')
          echo "example-apps=$example_apps" >> "$GITHUB_OUTPUT"
        working-directory: packages

  # Build example web apps job
  build:
    needs: find-example-apps
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        package: ${{ fromJson(needs.find-example-apps.outputs.example-apps) }}
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter web app
        run: flutter build web -v --release --base-href /${{ github.event.repository.name }}/${{ matrix.package }}/
        working-directory: packages/${{ matrix.package }}/example

      - name: Upload web build temporarily
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.package }}
          path: packages/${{ matrix.package }}/example/build/web
          retention-days: 1

  # Upload pages artifact to pages job
  upload-to-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all web builds
        uses: actions/download-artifact@v4
        with:
          path: site

      - name: Disable Jekyll
        run: touch site/.nojekyll

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'

  # Deploy job
  deploy-pages:
    needs: upload-to-pages
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
