# This workflow applies labels to pull requests based on the
# paths that are modified in the pull request.
#
# Edit `.github/labeler.yml` and `.github/post_merge_labeler.yml`
# to configure labels.
#
# For more information, see: https://github.com/actions/labeler
name: Label pull request

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
