# This workflow applies labels to pull requests based on the
# paths that are modified in the pull request.
#
# Edit `.github/labeler.yml` and `.github/post_merge_labeler.yml`
# to configure labels.
#
# For more information, see: https://github.com/actions/labeler
name: Label pull request

on:
  pull_request_target:
    types: [opened]

# Declare default permissions as read only.
permissions: read-all

jobs:
  label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
