name: Update fonts
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # Enable manual run from Github
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Flutter repository with beta channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta
      - run: flutter doctor -v
      - run: flutter pub get

      - run: dart pub global activate cider
      - run: dart generator/generator.dart

      - name: Read families_diff file
        uses: actions/github-script@v4
        id: get_families_diff
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('generator/families_diff','utf8').toString();
          result-encoding: string

      - name: Cancel workflow if there is no diff
        uses: andymckay/cancel-action@0.2
        if: steps.get_families_diff.outputs.result == ''

      - name: If cancelling workflow, allow for enough time to do so
        run: sleep 15s
        shell: bash
        if: steps.get_families_diff.outputs.result == ''

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MATERIAL_ROBOT_TOKEN }}
          committer: material-robot <featherless+materialrobot@google.com>
          commit-message: |
            [automated] update fonts

            ${{ steps.get_families_diff.outputs.result }}
          base: main
          branch: create-pull-request/update
          delete-branch: true
          author: material-robot <featherless+materialrobot@google.com>
          title: Update fonts
          body: |
            # Summary
            ${{ steps.get_families_diff.outputs.result }}

            Please note that all existing fonts are subject to being updated.
          team-reviewers: flutter-package-maintainers
          labels: automated
