name: Update fonts
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch: # Enable manual run from Github
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone Flutter repository with beta channel
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: beta
      - run: flutter doctor -v
      - run: flutter pub get

      - run: dart generator/generator.dart
      - name: Exit if there are no new fonts
        run: |
          if [ -s generator/fonts_latest_added ]; then 
            echo lib/google_fonts.dart has been updated.
          else 
            echo No new fonts. Exiting...
            exit 1
          fi

      - run: dart pub global activate cider
      - run: cider log changed 'Added the latest fonts from fonts.google.com'
      - run: cider bump minor
      - run: cider release

      - name: Read fonts_latest_added file
        uses: actions/github-script@v4
        id: getaddedfonts
        with:
          script: |
            const fs = require('fs');
            return fs.readFileSync('generator/fonts_latest_added','utf8').toString();
          result-encoding: string

      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.MATERIAL_ROBOT_TOKEN }}
          committer: material-robot <featherless+materialrobot@google.com>
          commit-message: |
            [automated] add fonts

            ${{ steps.getaddedfonts.outputs.result }}
          base: main
          branch: create-pull-request/update
          delete-branch: true
          author: material-robot <featherless+materialrobot@google.com>
          title: Update fonts
          body: |
            Adds the latest fonts from [Google Fonts](https://fonts.google.com):
            ${{ steps.getaddedfonts.outputs.result }}
          team-reviewers: google-fonts-flutter-package-maintainers
          labels: automated
